### ISSUE TITLE
[ROM Vertebrate Paleontology 48468] Dasypus bellus - Wrong GPS coordinates

### ISSUE THREAD

**Issue by fdelsuc** [rom-vertnet/vpfossils#21]
Longitude is positive instead of being negative 

.....................................................

You can [view the original detail page](http://portal.vertnet.org/o/rom/vertebrate-paleontology?id=48468) on VertNet. Here are the original record contents:
<table>
        <thead>
          <tr>
            <th>Term</th>
            <th>Value</th>
          </tr>
        </thead>
        <tbody>
        
                  
          <tr>
            <td>Modified</td>
            <td id="Modified">
              
                2015-04-15
              
            </td>
          </tr>
          
                  
          <tr>
            <td>Language</td>
            <td id="Language">
              
                en
              
            </td>
          </tr>
          
        
                  
          <tr>
            <td>RightsHolder</td>
            <td id="RightsHolder">
              
                Royal Ontario Museum; ROM
              
            </td>
          </tr>
          
                  
          <tr>
            <td>AccessRights</td>
            <td id="AccessRights">
              
                not-for-profit use only
              
            </td>
          </tr>
          
        
        
        
                  
          <tr>
            <td>CollectionID</td>
            <td id="CollectionID">
              
                urn:lsid:biocol.org:col:35306
              
            </td>
          </tr>
          
        
                  
          <tr>
            <td>InstitutionCode</td>
            <td id="InstitutionCode">
              
                ROM
              
            </td>
          </tr>
          
                  
          <tr>
            <td>CollectionCode</td>
            <td id="CollectionCode">
              
                Vertebrate Paleontology
              
            </td>
          </tr>
          
                  
          <tr>
            <td>DatasetName</td>
            <td id="DatasetName">
              
                Palaeobiology - Vertebrate Fossils Collection Mammalia
              
            </td>
          </tr>
          
        
                  
          <tr>
            <td>BasisOfRecord</td>
            <td id="BasisOfRecord">
              
                FossilSpecimen
              
            </td>
          </tr>
          
        
        
        
                  
          <tr>
            <td>OccurrenceID</td>
            <td id="OccurrenceID">
              
                URI:catalog:ROM: Palaeobiology - Vertebrate Fossils: 48468
              
            </td>
          </tr>
          
                  
          <tr>
            <td>CatalogNumber</td>
            <td id="CatalogNumber">
              
                48468
              
            </td>
          </tr>
          
        
                  
          <tr>
            <td>RecordNumber</td>
            <td id="RecordNumber">
              
                YELLOW GATE
              
            </td>
          </tr>
          
                  
          <tr>
            <td>RecordedBy</td>
            <td id="RecordedBy">
              
                Brayfield
              
            </td>
          </tr>
          
        
        
        
        
        
        
        
        
                  
          <tr>
            <td>Preparations</td>
            <td id="Preparations">
              
                OSTEODERM; IMBRICATING; COMPLETE
              
            </td>
          </tr>
          
                  
          <tr>
            <td>Disposition</td>
            <td id="Disposition">
              
                systematic collections
              
            </td>
          </tr>
          
        
        
        
                  
          <tr>
            <td>AssociatedReferences</td>
            <td id="AssociatedReferences">
              
                Kerr, S., Fermin, J. and K. Gaynor. 2012. Optimal localities for the excavation of vertebrate fossils: spatial relationships amongst fossils and fossil sites in Sarasota and Charlotte Counties, Florida. Unpublished report, on file
              
            </td>
          </tr>
          
        
        
        
        
        
        
                  
          <tr>
            <td>EventDate</td>
            <td id="EventDate">
              
                1974-12
              
            </td>
          </tr>
          
        
        
        
                  
          <tr>
            <td>Year</td>
            <td id="Year">
              
                1974
              
            </td>
          </tr>
          
                  
          <tr>
            <td>Month</td>
            <td id="Month">
              
                12
              
            </td>
          </tr>
          
        
                  
          <tr>
            <td>VerbatimEventDate</td>
            <td id="VerbatimEventDate">
              
                19741200
              
            </td>
          </tr>
          
        
        
        
        
        
        
                  
          <tr>
            <td>HigherGeography</td>
            <td id="HigherGeography">
              
                North America; USA; Florida; Charlotte County
              
            </td>
          </tr>
          
                  
          <tr>
            <td>Continent</td>
            <td id="Continent">
              
                North America
              
            </td>
          </tr>
          
        
        
        
                  
          <tr>
            <td>Country</td>
            <td id="Country">
              
                USA
              
            </td>
          </tr>
          
        
                  
          <tr>
            <td>StateProvince</td>
            <td id="StateProvince">
              
                Florida
              
            </td>
          </tr>
          
                  
          <tr>
            <td>County</td>
            <td id="County">
              
                Charlotte County
              
            </td>
          </tr>
          
        
                  
          <tr>
            <td>Locality</td>
            <td id="Locality">
              
                Port Charlotte, President Waterway,President Waterway; 22-21; E-41; S
              
            </td>
          </tr>
          
                  
          <tr>
            <td>VerbatimLocality</td>
            <td id="VerbatimLocality">
              
                Port Charlotte, President Waterway
              
            </td>
          </tr>
          
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
                  
          <tr>
            <td>DecimalLatitude</td>
            <td id="DecimalLatitude">
              
                26.8942761
              
            </td>
          </tr>
          
                  
          <tr>
            <td>DecimalLongitude</td>
            <td id="DecimalLongitude">
              
                82.1985676
              
            </td>
          </tr>
          
                  
          <tr>
            <td>GeodeticDatum</td>
            <td id="GeodeticDatum">
              
                WGS84
              
            </td>
          </tr>
          
                  
          <tr>
            <td>CoordinateUncertaintyInMeters</td>
            <td id="CoordinateUncertaintyInMeters">
              
                1000
              
            </td>
          </tr>
          
        
        
        
        
        
                  
          <tr>
            <td>GeoreferencedBy</td>
            <td id="GeoreferencedBy">
              
                Fermin, J; Gaynor, K; Kerr, S
              
            </td>
          </tr>
          
                  
          <tr>
            <td>GeoreferencedDate</td>
            <td id="GeoreferencedDate">
              
                2012-04-05
              
            </td>
          </tr>
          
                  
          <tr>
            <td>GeoreferenceProtocol</td>
            <td id="GeoreferenceProtocol">
              
                MaNIS/HerpNet/ORNIS Georeferencing Guidelines, GBIF Best Practices
              
            </td>
          </tr>
          
                  
          <tr>
            <td>GeoreferenceSources</td>
            <td id="GeoreferenceSources">
              
                BioGeomancer
              
            </td>
          </tr>
          
                  
          <tr>
            <td>GeoreferenceVerificationStatus</td>
            <td id="GeoreferenceVerificationStatus">
              
                verification required
              
            </td>
          </tr>
          
        
        
        
        
        
        
        
        
                  
          <tr>
            <td>EarliestEpochOrLowestSeries</td>
            <td id="EarliestEpochOrLowestSeries">
              
                Pleistocene
              
            </td>
          </tr>
          
        
        
        
        
        
        
        
        
        
        
        
                  
          <tr>
            <td>IdentifiedBy</td>
            <td id="IdentifiedBy">
              
                Iwama, B.
              
            </td>
          </tr>
          
                  
          <tr>
            <td>DateIdentified</td>
            <td id="DateIdentified">
              
                19990825
              
            </td>
          </tr>
          
        
        
        
        
        
        
        
        
        
        
        
        
        
                  
          <tr>
            <td>ScientificName</td>
            <td id="ScientificName">
              
                Dasypus bellus
              
            </td>
          </tr>
          
        
        
        
        
        
        
                  
          <tr>
            <td>HigherClassification</td>
            <td id="HigherClassification">
              
                Animalia; Chordata; Mammalia; Xenarthra; Dasypodidae; Dasypus
              
            </td>
          </tr>
          
                  
          <tr>
            <td>Kingdom</td>
            <td id="Kingdom">
              
                Animalia
              
            </td>
          </tr>
          
                  
          <tr>
            <td>Phylum</td>
            <td id="Phylum">
              
                Chordata
              
            </td>
          </tr>
          
                  
          <tr>
            <td>Class</td>
            <td id="Class">
              
                Mammalia
              
            </td>
          </tr>
          
                  
          <tr>
            <td>Order</td>
            <td id="Order">
              
                Xenarthra
              
            </td>
          </tr>
          
                  
          <tr>
            <td>Family</td>
            <td id="Family">
              
                Dasypodidae
              
            </td>
          </tr>
          
                  
          <tr>
            <td>Genus</td>
            <td id="Genus">
              
                Dasypus
              
            </td>
          </tr>
          
        
                  
          <tr>
            <td>SpecificEpithet</td>
            <td id="SpecificEpithet">
              
                bellus
              
            </td>
          </tr>
          
        
        
        
        
        
        
        
        
        
        
        </tbody>
      </table>

**Comment by bradmROM** [comment]
Thank you for pointing this issue out. I will correct and republish the data to our GBIF IPT.
